# Generated by Django 4.1.5 on 2023-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_site_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoverview',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='siteoverview',
            name='faq',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.AddField(
            model_name='appoverview',
            name='faq',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='faq',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteoverview',
            name='faq',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
