# Generated by Django 4.1.5 on 2023-10-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_app_applogo_alter_appoverview_bannerimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
