# Generated by Django 4.1.5 on 2023-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_app_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoverview',
            name='paymentMethods',
        ),
        migrations.AddField(
            model_name='appoverview',
            name='paymentMethods',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
