# Generated by Django 4.1.5 on 2023-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_appoverview_supportedandroiddevices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
