# Generated by Django 4.1.5 on 2023-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_site_slug_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='cons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='pros',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
