# Generated by Django 4.1.5 on 2023-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_site_cons_site_features_site_pros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
