# Generated by Django 4.1.5 on 2023-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_site_paymentmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepros',
            name='site',
        ),
        migrations.AddField(
            model_name='app',
            name='cons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='coverImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='pros',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='siteCons',
        ),
        migrations.DeleteModel(
            name='sitePros',
        ),
    ]
