# Generated by Django 4.1.5 on 2023-10-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_app_site_alter_appoverview_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='cms.site'),
        ),
    ]
