# Generated by Django 4.1.5 on 2023-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_app_bonus_alter_site_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='androidDownloadSteps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='bonusList',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='bonuses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='cons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='faq',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='howToChose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='howToDeposit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='howToDownload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='howToStartPlaying',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='iosDownloadSteps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='paymentMethods',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='pros',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='security',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='whatIsApp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
