# Generated by Django 4.1.5 on 2023-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_sport_androiddownloadsteps_sport_bonuslist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='opinion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
